name: Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  deploy_to_local:
    runs-on: [dgx-2]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t gblr:dev .
      
      - name: Remove Existing Docker
        run: |
          docker stop gblr || true
          docker rm gblr || true
    
      - name: Deploy to Docker
        run: |
          docker run -d --gpus all --privileged\
            -v /home/prepaire/clip/models/pkl:/app/cache/pkl \
            -p 8015:8000 --name gblr gblr:dev

    environment:
      name: env